//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpxViewer.Modules.ElevationProfile.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElevationProfileViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElevationProfileViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpxViewer.Modules.ElevationProfile.Views.ElevationProfileViewResources", typeof(ElevationProfileViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (km).
        /// </summary>
        public static string Axis_DistanceKm {
            get {
                return ResourceManager.GetString("Axis_DistanceKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation (m).
        /// </summary>
        public static string Axis_ElevationM {
            get {
                return ResourceManager.GetString("Axis_ElevationM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: .
        /// </summary>
        public static string Tooltip_Distance {
            get {
                return ResourceManager.GetString("Tooltip_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation: .
        /// </summary>
        public static string Tooltip_Elevation {
            get {
                return ResourceManager.GetString("Tooltip_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Tooltip_Km {
            get {
                return ResourceManager.GetString("Tooltip_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Tooltip_M {
            get {
                return ResourceManager.GetString("Tooltip_M", resourceCulture);
            }
        }
    }
}
